### PR TITLE
Inlining css styles from fornac.css and rnaplot.css into javascript (issue #5)

### PR DESCRIPTION
**Pull request by BurkovBA**
Peter,

So, I've inlined `fornac.css` completely and am looking to inline `rnaplot.css`.

I have 2 questions so far. 

First, was it right for me to apply css in `FornaContainer.update()`? It seems to work, but not sure, if it's a perfect solution: https://github.com/BurkovBA/fornac/blob/master/app/scripts/fornac.js#L1692

Second, I can't get the build system work to deliver changes to `dist/` - it chokes on uglification. When I say `gulp build`, it fails with the following error:

```
[17:10:01] gulp-debug: app/index.html

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2178:20)
    at eval (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2904:23)
    at Object.parse (eval at <anonymous> (/Users/burkov/Documents/Projects/ebi/fornac/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2915:7)
```
I have `gulp-cli` and `bower` installed globally and said `npm install` and `bower install`.

Thanks!

### CODE REVIEW

**Comment by pkerpedjiev** [comment]
One potential issue with applying styles in javascript is that if the RNA structure changes (e.g. somebody adds a link), the styles won't be applied to the newly created elements.  If you make the container editable, you should be able to add links by "shift" clicking nodes and dragging to other nodes. Can you make sure that the styles are applied to the new links?

As for the uglify error, it appears to be an old error that there may or may not be a solution to:

https://github.com/mishoo/UglifyJS2/issues/348

Unfortunately, I don't think I can offer any help beyond what is in that thread.

**Comment by BurkovBA** [comment]
@pkerpedjiev  Peter,

as for Uglify error - it was choking on javascript in html files. I'm not sure, what was wrong with it, so I just removed `html` goal from `gulp build` task. Instead, I made it process all the javascript files in `.tmp` folder and output them to `dist`. Downside is that index.html is not bundled into `dist`.

Could you explain, how to make a container editable? I can't see such a configuration object in FornaContainer. Thanks!

**Comment by BurkovBA** [comment]
@pkerpedjiev 
Came up with a better solution than this. Instead of dynamically adding styles to element, I'd better dynamically add `<link rel="stylesheet">` with your css, preceded by element selector. This shouldn't be breaking anything.

**Comment by BurkovBA** [comment]
@pkerpedjiev 
Ok, instead of applying styles to elements directly, I started to dynamically create `<link>` element on `<head>` that applies those styles.

Don't think that change could break anything (well, maybe formatting only). So ready for merge and release.

**Pull request closed without merging**
